/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Interface.PN_Balikan;
import Interface.PN_DetX2;
import Interface.PN_DetX3;
import Interface.PN_SPL;
import Interface.PN_Transpose2X2;
import Interface.PN_MatriksX2;
import Interface.PN_MatriksX3;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;




/**
 *
 * @author zero
 */
public class PN_Main extends javax.swing.JFrame {

    /**
     * Creates new form MatrixCalc
     * 
     */
    
    public PN_Main() {
        setTitle("Matrix Calculator");
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        
        int x = (screenSize.width -getHeight())/2;
        int y = (screenSize.height -getWidth())/2;
        
        setLocation(x, y);
        //DONEGAYSEEEE
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pn_Sidebar = new javax.swing.JPanel();
        Pn_menu = new javax.swing.JPanel();
        Lb_Title = new javax.swing.JLabel();
        BTN_Transpose = new javax.swing.JToggleButton();
        BTN_balikan = new javax.swing.JToggleButton();
        BTN_Determinan = new javax.swing.JToggleButton();
        BTN_PenjumlahanPengurangan = new javax.swing.JToggleButton();
        BTN_SPL = new javax.swing.JToggleButton();
        BTN_Keluar = new javax.swing.JToggleButton();
        IMG_Logo = new javax.swing.JLabel();
        LB_Footer = new javax.swing.JLabel();
        About = new javax.swing.JToggleButton();
        Pn_Main = new javax.swing.JPanel();
        Pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(51, 51, 51));
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.BorderLayout());

        Pn_Sidebar.setPreferredSize(new java.awt.Dimension(280, 600));
        Pn_Sidebar.setLayout(new javax.swing.BoxLayout(Pn_Sidebar, javax.swing.BoxLayout.LINE_AXIS));

        Pn_menu.setBackground(new java.awt.Color(51, 51, 51));
        Pn_menu.setPreferredSize(new java.awt.Dimension(300, 586));

        Lb_Title.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        Lb_Title.setForeground(new java.awt.Color(0, 153, 102));
        Lb_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_Title.setText("ALJABAR GEOMETRI");

        BTN_Transpose.setBackground(new java.awt.Color(0, 153, 102));
        BTN_Transpose.setText("Transpose Matriks");
        BTN_Transpose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_TransposeMouseClicked(evt);
            }
        });
        BTN_Transpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_TransposeActionPerformed(evt);
            }
        });

        BTN_balikan.setBackground(new java.awt.Color(0, 153, 102));
        BTN_balikan.setText("Balikan Matriks");
        BTN_balikan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_balikanMouseClicked(evt);
            }
        });

        BTN_Determinan.setBackground(new java.awt.Color(0, 153, 102));
        BTN_Determinan.setText("Determinan");
        BTN_Determinan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_DeterminanMouseClicked(evt);
            }
        });

        BTN_PenjumlahanPengurangan.setBackground(new java.awt.Color(0, 153, 102));
        BTN_PenjumlahanPengurangan.setText("Penjumlahan & Pengurangan");
        BTN_PenjumlahanPengurangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_PenjumlahanPenguranganMouseClicked(evt);
            }
        });
        BTN_PenjumlahanPengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PenjumlahanPenguranganActionPerformed(evt);
            }
        });

        BTN_SPL.setBackground(new java.awt.Color(0, 153, 102));
        BTN_SPL.setText("Solusi Persamaan Linear");
        BTN_SPL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_SPLMouseClicked(evt);
            }
        });
        BTN_SPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SPLActionPerformed(evt);
            }
        });

        BTN_Keluar.setBackground(new java.awt.Color(0, 153, 102));
        BTN_Keluar.setText("Keluar");
        BTN_Keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_KeluarMouseClicked(evt);
            }
        });
        BTN_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_KeluarActionPerformed(evt);
            }
        });

        IMG_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-c-100.png"))); // NOI18N

        LB_Footer.setFont(new java.awt.Font("Liberation Sans", 2, 10)); // NOI18N
        LB_Footer.setForeground(new java.awt.Color(255, 255, 255));
        LB_Footer.setText("@STT_Cipasung_2023");

        About.setBackground(new java.awt.Color(0, 153, 102));
        About.setText("About");
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
        });
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pn_menuLayout = new javax.swing.GroupLayout(Pn_menu);
        Pn_menu.setLayout(Pn_menuLayout);
        Pn_menuLayout.setHorizontalGroup(
            Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pn_menuLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(LB_Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(84, 84, 84))
            .addGroup(Pn_menuLayout.createSequentialGroup()
                .addGroup(Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_menuLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(About, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_Transpose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_balikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_Determinan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_PenjumlahanPengurangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_SPL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_Keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Pn_menuLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(IMG_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63)))
                .addGap(30, 30, 30))
        );
        Pn_menuLayout.setVerticalGroup(
            Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_menuLayout.createSequentialGroup()
                .addComponent(IMG_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(About, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_PenjumlahanPengurangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_Transpose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_balikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_Determinan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_SPL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_Keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(LB_Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(149, 149, 149))
        );

        Pn_Sidebar.add(Pn_menu);

        jPanel1.add(Pn_Sidebar, java.awt.BorderLayout.LINE_START);

        Pn_Main.setBackground(new java.awt.Color(51, 51, 51));
        Pn_Main.setMaximumSize(new java.awt.Dimension(32767, 40000));

        Pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout Pn_MainLayout = new javax.swing.GroupLayout(Pn_Main);
        Pn_Main.setLayout(Pn_MainLayout);
        Pn_MainLayout.setHorizontalGroup(
            Pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_MainLayout.createSequentialGroup()
                .addComponent(Pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(518, Short.MAX_VALUE))
        );
        Pn_MainLayout.setVerticalGroup(
            Pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_MainLayout.createSequentialGroup()
                .addComponent(Pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(530, Short.MAX_VALUE))
        );

        jPanel1.add(Pn_Main, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        Pn_utama.add(new PN_About());
        Pn_utama.repaint();
        Pn_utama.revalidate();   
        
    }//GEN-LAST:event_formWindowOpened

    private void BTN_PenjumlahanPenguranganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_PenjumlahanPenguranganMouseClicked
        // TODO add your handling code here:
        String menu= JOptionPane.showInputDialog("Pilih Matriks \n1. Matriks 2X2 \n2. Matriks 3X3");
        int chose=Integer.parseInt(menu);
        
        switch (chose) {
            case 1:
                var x2= new Interface.PN_MatriksX2();
                
                Pn_utama.removeAll();
                Pn_utama.add(new PN_MatriksX2());
                Pn_utama.repaint();
                Pn_utama.revalidate();
                
//                int a11=Integer.parseInt(x2.A11.getToolTipText());
//                int a12=Integer.parseInt(x2.getToolTipText());
//                int a21=Integer.parseInt(x2.getToolTipText());
//                int a22=Integer.parseInt(x2.getToolTipText());
//                
                
                break;
            case 2 : 
                Pn_utama.removeAll();
                Pn_utama.add(new PN_MatriksX3());
                Pn_utama.repaint();
                Pn_utama.revalidate();
                break;
            default:
                JOptionPane.showMessageDialog(null, "Menu yang anda Pilih tidak tersedia");
        }
    }//GEN-LAST:event_BTN_PenjumlahanPenguranganMouseClicked

    private void BTN_SPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SPLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_SPLActionPerformed

    private void BTN_TransposeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_TransposeMouseClicked
        // TODO add your handling code here:
        int chose = Integer.parseInt(JOptionPane.showInputDialog("Pilih Matriks : \n 1. Matrix 2X2\n 2.Matriks 3X3 "));
        switch (chose) {
            case 1:
                Pn_utama.removeAll();
                Pn_utama.add(new PN_Transpose2X2());
                Pn_utama.repaint();
                Pn_utama.revalidate();
                break;
            case 2: 
                Pn_utama.removeAll();
                Pn_utama.add(new PN_Transpose3x3());
                Pn_utama.repaint();
                Pn_utama.revalidate();
                break;
            default:
                JOptionPane.showMessageDialog(null,"Masukan anda Tidak Valid");
        }
        
        
    }//GEN-LAST:event_BTN_TransposeMouseClicked

    private void BTN_balikanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_balikanMouseClicked
        // TODO add your handling code here:
        Pn_utama.removeAll();
        Pn_utama.add(new PN_Balikan());
        Pn_utama.repaint();
        Pn_utama.revalidate();
    }//GEN-LAST:event_BTN_balikanMouseClicked

    private void BTN_DeterminanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_DeterminanMouseClicked
        // TODO add your handling code here:
        String menu= JOptionPane.showInputDialog("Pilih Matriks \n1. Matriks 2X2 \n2. Matriks 3X3");
        int chose=Integer.parseInt(menu);
        switch (chose) {
            case 1:
                Pn_utama.removeAll();
                Pn_utama.add(new PN_DetX2());
                Pn_utama.repaint();
                Pn_utama.revalidate();
                break;
            case 2 : 
                Pn_utama.removeAll();
                Pn_utama.add(new PN_DetX3());
                Pn_utama.repaint();
                Pn_utama.revalidate();
                break;
            default:
                JOptionPane.showMessageDialog(null, "Menu yang anda Pilih tidak tersedia");
        }
        
    }//GEN-LAST:event_BTN_DeterminanMouseClicked

    private void BTN_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_KeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_KeluarActionPerformed

    private void BTN_KeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_KeluarMouseClicked
        // TODO add your handling code here:
       int confirm= JOptionPane.showConfirmDialog(null, "Yakin ingin keluar ?");
       if( confirm == JOptionPane.YES_OPTION){
           dispose();
       }
    }//GEN-LAST:event_BTN_KeluarMouseClicked

    private void BTN_TransposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_TransposeActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_BTN_TransposeActionPerformed

    private void BTN_PenjumlahanPenguranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PenjumlahanPenguranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_PenjumlahanPenguranganActionPerformed

    private void BTN_SPLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_SPLMouseClicked
        // TODO add your handling code here:
        
        Pn_utama.removeAll();
                Pn_utama.add(new PN_SPL());
                Pn_utama.repaint();
                Pn_utama.revalidate();
    }//GEN-LAST:event_BTN_SPLMouseClicked

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
        // TODO add your handling code here:
        Pn_utama.removeAll();
        Pn_utama.add(new PN_About());
        Pn_utama.repaint();
        Pn_utama.revalidate();
    }//GEN-LAST:event_AboutMouseClicked

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PN_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PN_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PN_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PN_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PN_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton About;
    private javax.swing.JToggleButton BTN_Determinan;
    private javax.swing.JToggleButton BTN_Keluar;
    private javax.swing.JToggleButton BTN_PenjumlahanPengurangan;
    private javax.swing.JToggleButton BTN_SPL;
    private javax.swing.JToggleButton BTN_Transpose;
    private javax.swing.JToggleButton BTN_balikan;
    private javax.swing.JLabel IMG_Logo;
    private javax.swing.JLabel LB_Footer;
    private javax.swing.JLabel Lb_Title;
    private javax.swing.JPanel Pn_Main;
    private javax.swing.JPanel Pn_Sidebar;
    private javax.swing.JPanel Pn_menu;
    private javax.swing.JPanel Pn_utama;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    

   
}
